apiVersion: widgets.templates.krateo.io/v1beta1
kind: Card
metadata:
  name: page-service-register-row-card
  namespace: krateo-system
spec:
  resourcesRefs:
    items: []
  widgetData:
    allowedResources: []
    items: []
