apiVersion: widgets.templates.krateo.io/v1beta1
kind: Flex
metadata:
  annotations:
    krateo.io/allowed-resources: derived
    krateo.io/nav-label: Pod sizing
    krateo.io/nav-order: '100'
    krateo.io/nav-path: /pod-sizing-v1a
  name: page-pod-sizing-v1a
  namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
spec:
  resourcesRefs:
    items:
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: page-pod-sizing-v1a-row
        name: page-pod-sizing-v1a-row
        namespace: krateo-system
        resource: rows
        verb: GET
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: page-pod-sizing-v1a-header
        name: page-pod-sizing-v1a-header
        namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
        resource: pageheaders
        verb: GET
  widgetData:
    allowedResources:
      - rows
      - pageheaders
    gap: middle
    items:
      - resourceRefId: page-pod-sizing-v1a-row
      - resourceRefId: page-pod-sizing-v1a-header
    vertical: true
