apiVersion: widgets.templates.krateo.io/v1beta1
kind: PageHeader
metadata:
  name: page-platform-services-header
  namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
spec:
  resourcesRefs:
    items: []
  widgetData:
    title: Platform services
