apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: pod-sizing-table
  namespace: krateo-system
spec:
  widgetDataTemplate:
  - expression: ${ [ .rows[] | [ {valueKey:"name",kind:"jsonSchemaType",type:"string",stringValue:.name}, {valueKey:"cpuRequest",kind:"jsonSchemaType",type:"string",stringValue:.cpuRequest}, {valueKey:"cpuUsage",kind:"jsonSchemaType",type:"string",stringValue:.cpuUsage}, {valueKey:"overprovisioned",kind:"jsonSchemaType",type:"string",stringValue:.overprovisioned} ] ] }
    forPath: dataSource
  apiRef:
    name: pods-cpu-sizing
    namespace: krateo-system
  resourcesRefs:
    items: []
  widgetData:
    columns:
      - title: Pod Name
        valueKey: name
      - title: CPU Request
        valueKey: cpuRequest
      - title: CPU Usage
        valueKey: cpuUsage
      - title: Overprovisioned
        valueKey: overprovisioned
    allowedResources: []
