apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: pod-sizing-demo-table
  namespace: krateo-system
spec:
  widgetDataTemplate:
  - expression: ${ .items }
    forPath: dataSource
  apiRef:
    name: pod-sizing-demo-query
    namespace: krateo-system
  resourcesRefs:
    items: []
  widgetData:
    allowedResources: []
    columns:
      - title: Pod
        valueKey: pod
      - title: Requested
        valueKey: requested
      - title: Used
        valueKey: used
      - title: Utilization
        valueKey: utilization
      - title: Verdict
        valueKey: verdict
