apiVersion: widgets.templates.krateo.io/v1beta1
kind: Table
metadata:
  name: pod-sizing-table
  namespace: krateo-system
spec:
  widgetDataTemplate:
  - expression: '${ [ .items[]? | [ {valueKey: "name", kind: "jsonSchemaType", type: "string", stringValue: .name}, {valueKey: "cpuRequest", kind: "jsonSchemaType", type: "string", stringValue: .cpuRequest}, {valueKey: "cpuUsage", kind: "jsonSchemaType", type: "string", stringValue: .cpuUsage}, {valueKey: "verdict", kind: "jsonSchemaType", type: "string", stringValue: .verdict} ] ] }'
    forPath: dataSource
  apiRef:
    name: pod-sizing
    namespace: krateo-system
  resourcesRefs:
    items: []
  widgetData:
    allowedResources: []
    columns:
      - title: Pod Name
        valueKey: name
      - title: CPU Request
        valueKey: cpuRequest
      - title: CPU Usage
        valueKey: cpuUsage
      - title: Status / Provisioning
        valueKey: verdict
